language: php
php:
  - 7.0
  - 5.5
  - 5.4
before_script:
  - mysql -e 'create database sitemaster_test;'
  - php scripts/install.php
script:
  - phpunit --verbose --bootstrap tests/init.php tests
  - phpunit --verbose --bootstrap tests/init.php plugins/metric_links/tests
